/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b51dab81-df72-48b0-b7f9-daf1c218c878",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wIWopIuo3",
    "aws_user_pools_web_client_id": "62e1mm5dni5095mhj7ooachdea",

    "aws_appsync_graphqlEndpoint": "https://5ta6xwlu5jay7hzafjwmrb64xy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-r5cmuhrnonfg5keenon4qxcwni",
    "oauth": {}
};


export default awsmobile;


// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.