/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b51dab81-df72-48b0-b7f9-daf1c218c878",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wIWopIuo3",
    "aws_user_pools_web_client_id": "62e1mm5dni5095mhj7ooachdea",
    "oauth": {}
};


export default awsmobile;
